# Generated by Django 3.0 on 2020-09-12 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('doctor_name', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('others', 'others')], default=None, max_length=7)),
                ('age', models.IntegerField()),
                ('contact', models.CharField(blank=True, default=None, max_length=10)),
                ('address', models.CharField(blank=True, default=None, max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='imageInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eye_image', models.FileField(upload_to='')),
                ('Patient_info', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='predictor.Patient_info')),
            ],
        ),
    ]
